<div class="flex flex-col">
	<div class="min-w-screen bg-gray-200 flex items-center justify-center px-5 py-5">
		<div class="w-full max-w-3xl">
			<div class="-mx-2 md:flex">
				<div class="w-full md:w-1/2 px-2">
					<div class="rounded-lg shadow-sm mb-4">
						<div class="rounded-lg bg-white shadow-lg md:shadow-xl relative overflow-hidden">
							<div class="px-3 pt-4 pb-4 text-center relative z-10">
								<h4 class="text-sm uppercase text-gray-500 leading-tight">Total number of Courses</h4>
								<h3 class="text-3xl text-gray-700 font-semibold leading-tight my-3"><?php echo $this->view_data['num_courses'] ?></h3>
							</div>
							<div class="absolute bottom-0 inset-x-0">
								<canvas id="chart1" height="70"></canvas>
							</div>
						</div>
					</div>
				</div>
				<div class="w-full md:w-1/2 px-2">
					<div class="rounded-lg shadow-sm mb-4">
						<div class="rounded-lg bg-white shadow-lg md:shadow-xl relative overflow-hidden">
							<div class="px-3 pt-4 pb-4 text-center relative z-10">
								<h4 class="text-sm uppercase text-gray-500 leading-tight">Total number of Students</h4>
								<h3 class="text-3xl text-gray-700 font-semibold leading-tight my-3"><?php echo $this->view_data['num_students'] ?></h3>
							</div>
							<div class="absolute bottom-0 inset-x-0">
								<canvas id="chart2" height="70"></canvas>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>	
	</div>
	
	<div>
		
		<div class="container mx-auto px-4 sm:px-8">
			<div class="py-8">
				
				<div class="mb-4 flex justify-between items-center">
					<div class="flex-1 pr-4">
						<h2 class="text-2xl font-semibold leading-tight">Courses</h2>
					</div>
					<div >
						<!--<div class="relative md:w-full">
							<input type="search" class="w-full pl-10 pr-4 py-2 rounded-lg shadow focus:outline-none focus:shadow-outline text-gray-600 font-medium" placeholder="Search...">
							<div class="absolute top-0 left-0 inline-flex items-center p-2">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-400" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
									<rect x="0" y="0" width="24" height="24" stroke="none"></rect>
									<circle cx="10" cy="10" r="7"></circle>
									<line x1="21" y1="21" x2="15" y2="15"></line>
								</svg>
							</div>
						</div>-->
					</div>					
				</div>
				<div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
					<div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
						<table class="min-w-full leading-normal">
							<thead>
								<tr>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Course Name
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Number of Enrolled Students
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Number of Chapters
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Created Date
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								$classroom = $this->view_data['classroom'];
								foreach($classroom as $class){
									echo '<tr>
											<td class="px-5 py-5 hover:bg-gray-200 cursor-pointer border-b border-gray-200 bg-white text-sm">
												<a href="classroom/view/?'.$class['course_ID'].'">
													<div class="flex items-center">
														<div class="flex-shrink-0 w-10 h-10">
															<img class="w-full h-full rounded-lg" src="'.DOMAIN.'data/courses/'.$class['image'].'" alt="">
														</div>
														<div class="ml-3">
															<p class="text-gray-900 whitespace-no-wrap">
																'.$class['title'].'
															</p>
														</div>
													</div>
												</a>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.$class['enrolled'].'</p>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.$class['chapters'].'</p>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.date("d M Y", strtotime($class['date'])).'</p>
											</td>
										</tr>';
								}
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>