<?php
$ebooks = $this->view_data['books'];
?>
<div class="flex flex-col">
	<div class="min-w-screen bg-gray-200 flex items-center justify-center px-5 py-5">
		<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex  my-2">
			<form action="save" method="post" enctype="multipart/form-data" class="mb-6">
				<input type="hidden" value="<?php echo(parse_url($_SERVER['REQUEST_URI'], PHP_URL_QUERY)) ?>" name="course_ID" hidden>
				<div class="px-3 mb-6 ">
					<img class="h-64 w-128 object-cover rounded-lg pb-5/6" src="https://placeholder.pics/svg/300" id="poster" alt="Book">
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="book_image" type="file" accept="image/x-png,image/gif,image/jpeg">
				</div>
				<div class="px-3 mb-6 ">
					<label class="block uppercase tracking-wide text-grey-darker text-xs font-bold mb-2" for="grid-first-name">Book Title</label>
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="title" type="text" placeholder="Put Title here">
					<p class="text-red text-xs italic">Please fill out this field.</p>
				</div>
				<div class="flex items-center justify-end">
					<button type="submit" name="Save" class="bg-blue-600 text-gray-200 px-2 py-2 rounded-md">SAVE</button>
				</div>
			</form>
		</div>
	</div>
</div>
<div class="lg:px-6 mt-4 bg-white w-full text-gray-700 text-lg px-4 lg:px-0 leading-relaxed">
	<h1 class="text-2xl text-gray-800 font-semibold mb-4 mt-4">Course Books</h1>
	<div class="flex items-center justify-center">
		<?php
		foreach($ebooks as $book){
			echo '<div class="flex flex-col justify-center items-center max-w-sm mx-auto my-8">
				    <div style="background-image: url('.DOMAIN.'data/books/'.$book['cover_image'].'"
					   class="bg-gray-300 h-64 w-full rounded-lg shadow-md bg-cover bg-center"></div>
						<div class="w-56 md:w-64 bg-white -mt-10 shadow-lg rounded-lg overflow-hidden">
							<div class="flex items-center justify-between py-2 px-3 bg-gray-400">
								<h1 class="text-gray-800 font-bold ">'.$book['name'].'</h1>
							</div>
							<div class="flex items-center w-full">
								<a href="'.DOMAIN.'dashboard/classroom/library/remove?uuid='.$book['uuid'].'" class="bg-red-600 w-full text-gray-200 px-2 py-2 rounded-md">DELETE</a>
							</div>
						</div>
					</div>';
		}
		?>	
	</div>
</div>
<script>
var ImgInput = document.getElementsByName('book_image')[0];
    Displayer = document.getElementById('poster');
ImgInput.addEventListener('change', function() {
    Displayer.src = window.URL.createObjectURL(ImgInput.files[0])
})
</script>