<div class="flex flex-col">
	<div class="min-w-screen bg-gray-200 flex items-center justify-center px-5 py-5">
		<main class="container mx-auto max-w-screen-lg h-full">
			<!-- file upload modal -->
			<article aria-label="File Upload Modal" class="relative h-full flex flex-col bg-white shadow-xl rounded-md" ondrop="dropHandler(event);" ondragover="dragOverHandler(event);" ondragleave="dragLeaveHandler(event);" ondragenter="dragEnterHandler(event);">
				
				<!-- scroll area -->
				<section class="h-full overflow-auto p-8 w-full h-full flex flex-col">
					<header class="border-dashed border-2 border-gray-400 py-12 flex flex-col justify-center items-center">
						<p class="mb-3 font-semibold text-gray-900 flex flex-wrap justify-center">
							<span>Drag and drop your</span>&nbsp;<span>files anywhere or</span>
						</p>
						<input id="hidden-input" type="file" name="multifile" class="hidden" />
						<button id="button" class="mt-2 rounded-sm px-3 py-1 bg-gray-200 hover:bg-gray-300 focus:shadow-outline focus:outline-none">
						Upload a file
						</button>
					</header>
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mt-3 hidden" id="file_name" type="text" placeholder="File Name" disabled>
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mt-3" id="title" name="filename" type="text" placeholder="File Title" required>
					<select class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mt-3" id="selectChapter" name="chapter" required>
						<option disabled selected value="none">Select Chapter Unit</option>
						<?php
							$chapters = $this->view_data['chapters'];
							foreach($chapters as $unit){
								echo '<option value="'.$unit['chapter_ID'].'">'.$unit['name'].'</option>';
							}
						?>
					</select>
				</section>

				<!-- sticky footer -->
				<footer class="flex justify-end px-8 pb-8 pt-4">
					<button id="submit" id="uploadBtn" class="rounded-sm px-3 py-1 bg-blue-700 hover:bg-blue-500 text-white focus:shadow-outline focus:outline-none">
					Upload now
					</button>
				</footer>
			</article>
		</main>
	</div>
	
	<div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
		<div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
			<table class="min-w-full leading-normal">
				<thead>
					<tr>
						<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
							File Title
						</th>
						<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
							File Type
						</th>
						<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
							Action
						</th>
					</tr>
				</thead>
				<tbody>
					<?php
					$files = $this->view_data['files'];
					foreach($files as $file){
						echo '<tr>
								<td class="px-5 py-5 hover:bg-gray-200 cursor-pointer border-b border-gray-200 bg-white text-sm">
										<div class="flex items-center">
											<div class="ml-3">
												<p class="text-gray-900 whitespace-no-wrap">
													'.$file['file_name'].'
												</p>
											</div>
										</div>
								</td>
								<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
									<p class="text-gray-900 whitespace-no-wrap">'.$file['source_type'].'</p>
								</td>
								<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
									<a href="'.DOMAIN.'dashboard/classroom/filemanager/remove?fid='.$file['file_ID'].'" class="bg-red-600 w-full text-gray-200 px-2 py-2 rounded-md">DELETE</a>
								</td>
							</tr>';
					}
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>



<script>
const filename = document.querySelector('#file_name');
	  uploadBtn = document.querySelector('#uploadBtn');
	  Title = document.querySelector('#title');
	  chapter = document.querySelector('#selectChapter');
	  inputfile = document.querySelector('#hidden-input');
	  bool = false;

document.getElementById("button").onclick = () => inputfile.click();
inputfile.addEventListener('change', function() {
    filename.value = inputfile.files[0].name;
	filename.classList.remove('hidden');
	bool = true;
})

document.getElementById("submit").onclick = () => {
	
	if(Title.value.trim() !== "" && chapter.value !== 'none' && bool){
		var formData = new FormData();
		formData.append('course_ID', '<?php echo $this->view_data['course_ID'] ?>');
		formData.append('chapter_ID', chapter.value);
		formData.append('title', Title.value.trim());
		formData.append("files", inputfile.files[0]);
		
		var xhr = new XMLHttpRequest();
		xhr.open('POST', '<?php echo DOMAIN?>dashboard/classroom/filemanager/save', true);
		xhr.onload = function () {
			if(this.responseText == 'success'){
				window.location.reload(true);
			}else{
				alert(this.responseText);
			}
		};
		xhr.send(formData);
	}else{
		alert('Please fill all Fields');
	}	
};

</script>