<?php
$course = $this->view_data['course'];
$chapters = $this->view_data['chapters'];
$students = $this->view_data['students'];
?>
<div class="flex flex-col">
	<div class="min-w-screen bg-gray-200 flex items-center justify-center px-5 py-5">
		<div class="md:flex shadow-lg  mx-6 md:mx-auto max-w-lg md:max-w-2xl h-64">
			<img class="h-full w-full md:w-1/3  object-cover rounded-lg rounded-r-none pb-5/6" src="<?php echo DOMAIN.'data/courses/'.$course['cover_image']?>" alt="Course">
			<div class="w-full md:w-2/3 px-4 py-4 bg-white rounded-lg">
				<div class="flex items-center">
					<h2 class="text-xl text-gray-800 font-medium mr-auto"><?php echo $course['title']?></h2>
				</div>
				<hr>
				<p class="text-gray-800 font-semibold tracking-tighter"><?php echo date("d M Y", strtotime($course['created_date']))?></p>
				<p class="text-sm text-gray-700 mt-4">
					<span class="font-bold">Chapter:</span><br>
					<?php
						foreach($chapters as $class){
							echo '<span>'.$class['name'].'</span><br>';
						}
					?>		
				</p>
				<div class="flex items-center justify-end mt-4 top-auto">
					<!--<a href="<?php echo DOMAIN.'dashboard/classroom/delete/?'.(parse_url($_SERVER['REQUEST_URI'], PHP_URL_QUERY)) ?>" class="bg-white text-red-500 px-4 py-2 rounded mr-auto hover:underline">Delete</a>-->
					<a href="<?php echo DOMAIN.'dashboard/classroom/edit/?'.(parse_url($_SERVER['REQUEST_URI'], PHP_URL_QUERY)) ?>" class="bg-orange-200 text-blue-600 px-2 py-2 rounded-md mr-2">Edit</a>
					<a href="<?php echo DOMAIN.'dashboard/classroom/preview?cuid='.(parse_url($_SERVER['REQUEST_URI'], PHP_URL_QUERY)) ?>" class="bg-orange-500 text-gray-200 px-2 py-2 rounded-md">Preview</a>
				</div>
			</div>
		</div>
		
	</div>
	<div class="md:flex mx-6 md:mx-auto max-w-lg md:max-w-2xl">
		<a href="<?php echo DOMAIN.'dashboard/classroom/filemanager/?'.(parse_url($_SERVER['REQUEST_URI'], PHP_URL_QUERY)) ?>" class="bg-orange-500 shadow-lg text-gray-200 px-2 py-2 rounded-lg ">File Manager</a>
	</div>
	
	<div>
		
		<div class="container mx-auto px-4 sm:px-8">
			<div class="py-8">
				
				<div class="mb-4 flex justify-between items-center">
					<div class="flex-1 pr-4">
						<h2 class="text-2xl font-semibold leading-tight">Enrolled Students</h2>
					</div>
					<div >
						<!--<div class="relative md:w-full">
							<input type="search" class="w-full pl-10 pr-4 py-2 rounded-lg shadow focus:outline-none focus:shadow-outline text-gray-600 font-medium" placeholder="Search...">
							<div class="absolute top-0 left-0 inline-flex items-center p-2">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-400" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
									<rect x="0" y="0" width="24" height="24" stroke="none"></rect>
									<circle cx="10" cy="10" r="7"></circle>
									<line x1="21" y1="21" x2="15" y2="15"></line>
								</svg>
							</div>
						</div>-->
					</div>					
				</div>
				<div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
					<div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
						<table class="min-w-full leading-normal">
							<thead>
								<tr>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										FullName
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Enrolled Course
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Completion Level
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Last Login
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								$students = $this->view_data['students'];
								foreach($students as $person){
									$level = 'bg-red-200';
									if($person['completion'] > 33.3){$level = 'bg-yellow-200';}
									if($person['completion'] > 70){$level = 'bg-green-200';}
									echo '<tr>
											<td class="px-5 py-5 hover:bg-gray-200 cursor-pointer border-b border-gray-200 bg-white text-sm">
												<a href="'.DOMAIN.'dashboard/students">
													<div class="flex items-center">
														<div class="flex-shrink-0 w-10 h-10">
															<img class="w-full h-full rounded-lg" src="'.DOMAIN.'data/accounts/profile/'.$person['image'].'" alt="">
														</div>
														<div class="ml-3">
															<p class="text-gray-900 whitespace-no-wrap">
																'.$person['fullname'].'
															</p>
														</div>
													</div>
												</a>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.$person['course'].'</p>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<span class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
													<span aria-hidden="" class="absolute inset-0 '.$level.' opacity-50 rounded-full"></span>
													<span class="relative">'.round($person['completion']).'%</span>
												</span>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.date("d M Y", strtotime($person['last_login'])).'</p>
											</td>
										</tr>';
								}
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		
	</div>
	
	<div>
		
		<div class="container mx-auto px-4 sm:px-8">
			<div class="py-8">
				
				<div class="mb-4 flex justify-between items-center">
					<div class="flex-1 pr-4">
						<h2 class="text-2xl font-semibold leading-tight">Course Chapters</h2>
					</div>	
					<a href="<?php echo DOMAIN.'dashboard/classroom/chapter/add/?'.(parse_url($_SERVER['REQUEST_URI'], PHP_URL_QUERY)) ?>" class="bg-orange-600 shadow-lg text-gray-200 px-2 py-2 rounded-lg mr-4">Add Chapter</a>
				</div>
				<div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
					<div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
						<table class="min-w-full leading-normal">
							<thead>
								<tr>
									<th class="px-3 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Chapter Title
									</th>
									<th class="px-3 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										
									</th>
									<th class="px-3 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Chapter Position
									</th>
									<th class="px-3 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Created Date
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								foreach($chapters as $class){
									
									echo '<tr>
											<td class="px-5 py-5 hover:bg-gray-200 cursor-pointer border-b border-gray-200 bg-white text-sm">
												<a href="'.DOMAIN.'dashboard/classroom/chapter/edit/?cuid='.$class['course_ID'].'&chid='.$class['chapter_ID'].'">
													<div class="flex items-center">
														<div class="ml-3">
															<p class="text-gray-900 whitespace-no-wrap">'.$class['name'].'</p>
														</div>
													</div>
												</a>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm"></td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.$class['rank_position'].'</p>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.date("d M Y", strtotime($class['created_date'])).'</p>
											</td>
										</tr>	';
								}
								?>						
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>