<div class="flex flex-col">
	<div>
		<div class="container mx-auto px-4 sm:px-8">
			<div class="py-8">
				
				<div class="mb-4 flex justify-between items-center">
					<div class="flex-1 pr-4">
						<h2 class="text-2xl font-semibold leading-tight">Your Students</h2>
					</div>
					<div >
						<!--<div class="relative md:w-full">
							<input type="search" class="w-full pl-10 pr-4 py-2 rounded-lg shadow focus:outline-none focus:shadow-outline text-gray-600 font-medium" placeholder="Search...">
							<div class="absolute top-0 left-0 inline-flex items-center p-2">
								<svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-400" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
									<rect x="0" y="0" width="24" height="24" stroke="none"></rect>
									<circle cx="10" cy="10" r="7"></circle>
									<line x1="21" y1="21" x2="15" y2="15"></line>
								</svg>
							</div>
						</div>-->
					</div>					
				</div>
				<div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
					<div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
						<table class="min-w-full leading-normal">
							<thead>
								<tr>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Fullname
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Phone Number
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Birth Date
									</th>
									<th class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
										Last Login
									</th>
								</tr>
							</thead>
							<tbody>
								<?php
								$students = $this->view_data['students'];
								foreach($students as $student){
									$person = $student[0];
									echo '<tr>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<div>
													<div class="flex items-center">
														<div class="flex-shrink-0 w-10 h-10">
															<img class="w-full h-full rounded-full" src="'.DOMAIN.'data/accounts/profile/'.$person['profile_image'].'" alt="Profile Picture">
														</div>
														<div class="ml-3">
															<p class="text-gray-900 whitespace-no-wrap">
																'.$person['fullname'].'
															</p>
														</div>
													</div>
												</div>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.$person['phone_number'].'</p>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.date("d M Y", strtotime($person['birth_date'])).'</p>
											</td>
											<td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
												<p class="text-gray-900 whitespace-no-wrap">'.date("d M Y", strtotime($person['last_login_date'])).'</p>
											</td>
										</tr>';
								}
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		
	</div>
</div>