<div class="flex flex-col">
	<form action="" id="myform" method="post" enctype="multipart/form-data">
	<div class="min-w-screen bg-gray-200 flex items-center justify-center px-5 py-5">
		<div class="md:flex shadow-lg  mx-6 md:mx-auto max-w-lg md:max-w-2xl h-64">
			<img class="h-full w-full md:w-1/3  object-cover rounded-lg rounded-r-none pb-5/6" id="poster" src="https://placeholder.pics/svg/300" alt="Profile">
				<input name="cover_image" type="file" accept="image/x-png,image/gif,image/jpeg" required hidden>
			<div class="w-full md:w-2/3 px-4 py-4 bg-white rounded-lg">
				<div class="flex items-center">
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="name" type="text" placeholder="Fullname" required>
				</div>
				<div class="flex items-center">
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="email" type="text" placeholder="Email Address" required>
				</div>
				<div class="flex items-center">
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="phone" type="text" placeholder="Phone Number" required>
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="address" type="text" placeholder="Address" >
				</div>
				<div class="flex items-center">
					<input class="appearance-none block w-full bg-grey-lighter text-grey-darker border border-red rounded py-3 px-4 mb-3" name="birth" type="text" placeholder="Birth Date (Y/m/d)" required>
				</div>
			</div>
		</div>
	</div>
	<div class="md:flex mx-6 md:mx-auto max-w-lg md:max-w-2xl">
		<button type="button" id="photoBtn" class="mx-auto bg-purple-900 shadow-lg text-gray-200 px-2 py-2 rounded-lg mr-4">Select Image</button>
		<button type="submit" id="submitBtn" class="mx-auto bg-purple-900 shadow-lg text-gray-200 px-2 py-2 rounded-lg ">Save Account</button>
	</div>
	</form>
</div>

<script>
var photoBtn = document.querySelector('#photoBtn');
var submitBtn = document.querySelector('#submitBtn');
var ImgInput = document.getElementsByName('cover_image')[0];
Displayer = document.getElementById('poster');

submitBtn.addEventListener('click', function() {
    document.getElementById("myform").submit();
})
photoBtn.addEventListener('click', function() {
    ImgInput.click();
})
ImgInput.addEventListener('change', function() {
    Displayer.src = window.URL.createObjectURL(ImgInput.files[0])
})
</script>