<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title><?php echo TITLE ?> - Classroom Course</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo DOMAIN ?>assets/images/favicon.ico">

	<!-- CSS here -->
	<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css"> -->
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/tailwind.min.css">
	<link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/style.css">
	<link rel="stylesheet" href="http://svgicons.sparkk.fr/svgicons.css">
	
	<!-- JS here -->
	<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js" defer></script>
</head>
<body style="background: #edf2f7;">